version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "07:00"
      timezone: "America/New_York"
    versioning-strategy: increase
